-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLbkx7kra2cbwH7rG
NmI6FpL1tZxFDIfYWSCFZv4wPVygCgYIKoZIzj0DAQehRANCAAStLnJiYTWjsjHr
NhuvddrhlLnS3WTFh+GxMEXN02aN8w5EauL+s882wdBL5wULciJd2CWs3zNl7uJC
MelQX18W
-----END PRIVATE KEY-----